[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm install --include=dev']

[phases.build]
cmds = [
  './node_modules/.bin/prisma generate',
  './node_modules/.bin/tsc'
]

[start]
cmd = 'node dist/index.js'