[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm install --include=dev']

[phases.build]
cmds = ['npx prisma generate', './node_modules/.bin/tsc']

[start]
cmd = 'node dist/index.js'