[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = [
  "node node_modules/prisma/build/index.js generate",
  "node node_modules/typescript/bin/tsc"
]

[start]
cmd = "node dist/index.js"